QUALIFY_INTERVIEW_GROUPS = [
    {
        "number": 1,
        "title": 'Sofre ou sofreu de alguma doença infecciosa ou parasitária como:',
        "document_title": 'Sofre ou sofreu de alguma doença infecciosa ou parasitária como:',
        "items": [
            {"key": 'is_hiv', "label": 'Portador do vírus HIV ou pessoa vivendo com HIV?', "document_label": 'Portador do vírus HIV ou pessoa vivendo com HIV?'},
            {"key": 'is_chagas', "label": 'Doença de Chagas?', "document_label": 'Doença de Chagas?'},
            {"key": 'is_hanseniase', "label": 'Hanseníase?', "document_label": 'Hanseníase ?'},
            {"key": 'is_meningite', "label": 'Meningite?', "document_label": 'Meningite?'},
            {"key": 'is_tuberculose', "label": 'Tuberculose?', "document_label": 'Tuberculose?'},
            {"key": 'is_hepatite', "label": 'Hepatite?', "document_label": 'Hepatite?'},
        ],
    },
    {
        "number": 2,
        "title": 'Sofre ou sofreu de neoplasias malignas (câncer)?',
        "document_title": 'Sofre ou sofreu, de neoplasias malignas (câncer)?',
        "items": [
            {"key": 'is_aparelho_digestivo_cancer', "label": 'Aparelho digestivo (estômago, outros)?', "document_label": 'Aparelho digestivo (estomago, outros)?'},
            {"key": 'is_aparelho_respiratorio_cancer', "label": 'Aparelho respiratório (pulmão, outros)?', "document_label": 'Aparelho respiratório (pulmão, outros)?'},
            {"key": 'is_leucemia', "label": 'Leucemia?', "document_label": 'Leucemia?'},
            {"key": 'is_linfoma', "label": 'Linfoma?', "document_label": 'Linfoma?'},
            {"key": 'is_mama_cancer', "label": 'Mama?', "document_label": 'Mama?'},
            {"key": 'is_genitais_femininos', "label": 'Órgãos genitais femininos (câncer) - útero, ovário, outros?', "document_label": 'Órgãos genitais femininos (útero, ovário, outros)?'},
            {"key": 'is_genitais_masculinos', "label": 'Órgãos genitais masculinos (câncer) - próstata, outros?', "document_label": 'Órgãos genitais masculinos (próstata, outros)?'},
            {"key": 'is_pele', "label": 'Pele?', "document_label": 'Pele?'},
            {"key": 'is_tireoide', "label": 'Tireóide (câncer)?', "document_label": 'Tireóide?'},
            {"key": 'is_trato_urinario_cancer', "label": 'Trato urinário (rins, bexiga, outros)?', "document_label": 'Trato urinário (rins, bexiga, outros)?'},
        ],
    },
    {
        "number": 3,
        "title": 'Sofre ou sofreu de neoplasias benignas?',
        "document_title": 'Sofre ou sofreu, de neoplasias benignas?',
        "items": [
            {"key": 'is_tireoide_benigna', "label": 'Tireóide (nódulo benigno)?', "document_label": 'Tireoide?'},
            {"key": 'is_genitais_femininos_benigna', "label": 'Órgãos genitais femininos (tumor benigno) - útero, ovário, outros?', "document_label": 'Órgãos genitais femininos (útero, ovário, outros)?'},
        ],
    },
    {
        "number": 4,
        "title": 'Sofre ou sofreu de doenças do sangue?',
        "document_title": 'Sofre ou sofreu de doenças do sangue?',
        "items": [
            {"key": 'is_anemia', "label": 'Anemia?', "document_label": 'Anemia?'},
            {"key": 'is_coagulacao_hemofilias', "label": 'Doenças da coagulação ou hemofilias?', "document_label": 'Doenças da coagulação ou hemofilias?'},
            {"key": 'is_purpura', "label": 'Púrpura?', "document_label": 'Púrpura?'},
        ],
    },
    {
        "number": 5,
        "title": 'Sofre ou sofreu de doenças endócrinas e relacionadas?',
        "document_title": 'Sofre ou sofreu de doenças endócrinas e relacionadas?',
        "items": [
            {"key": 'is_diabetes', "label": 'Diabetes?', "document_label": 'Diabetes?'},
            {"key": 'is_tireoide_endocrina', "label": 'Distúrbio de tireóide?', "document_label": 'Tireóide?'},
            {"key": 'is_hipofise', "label": 'Distúrbio de hipófise?', "document_label": 'Hipófise?'},
            {"key": 'is_suprarrenal', "label": 'Distúrbio de supra renal?', "document_label": 'Supra renal?'},
            {"key": 'peso_kg', "label": 'Peso', "document_label": 'Especifique o seu peso Kg', "type": 'measure', "unit": 'kg'},
            {"key": 'altura_cm', "label": 'Altura', "document_label": 'Especifique a sua altura m cm', "type": 'measure', "unit": 'cm'},
            {"key": 'idade', "document_label": 'Qual a sua idade', "type": 'computed'},
            {"key": 'imc', "document_label": 'Cálculo IMC = Peso Corporal (Kg) / Estatura (m) x Estatura (m)', "type": 'imc'},
        ],
    },
    {
        "number": 6,
        "title": 'Sofre ou sofreu de transtornos psiquiátricos, mentais ou de identidade sexual?',
        "document_title": 'Sofre ou sofreu de transtornos psiquiátricos, mentais ou de identidade sexual?',
        "items": [
            {"key": 'is_psicose_esquizofrenia', "label": 'Psicose ou esquizofrenia?', "document_label": 'Psicose ou esquizofrenia?'},
            {"key": 'is_autismo', "label": 'Autismo?', "document_label": 'Autismo?'},
            {"key": 'is_depressao', "label": 'Depressão?', "document_label": 'Depressão'},
            {"key": 'is_transtorno_identidade_sexual', "label": 'Possui diagnóstico de transtorno de identidade sexual?', "document_label": 'Possui diagnóstico Transtorno de identidade sexual. Se a resposta for positiva, está sendo acompanhado em atenção especializada no processo transexualizador?'},
        ],
    },
    {
        "number": 7,
        "title": 'Sofre ou sofreu de doenças do sistema nervoso?',
        "document_title": 'Sofre ou sofreu de doenças do sistema nervoso?',
        "items": [
            {"key": 'is_avc', "label": 'Acidente vascular cerebral ("derrame"/AVC) ou sequelas?', "document_label": 'Acidente vascular cerebral (“derrame” “AVC”) ou sequelas?'},
            {"key": 'is_enxaqueca', "label": 'Enxaqueca ou outro tipo de cefaleia?', "document_label": 'Enxaqueca ou outro tipo de cefaleia?'},
            {"key": 'is_alzheimer', "label": 'Alzheimer?', "document_label": 'Alzheimer?'},
            {"key": 'is_epilepsia', "label": 'Epilepsia?', "document_label": 'Epilepsia?'},
            {"key": 'is_esclerose_multipla', "label": 'Esclerose múltipla?', "document_label": 'Esclerose múltipla'},
            {"key": 'is_paralisia_cerebral', "label": 'Paralisia cerebral?', "document_label": 'Paralisia cerebral?'},
            {"key": 'is_paralisias_polineuropatias', "label": 'Paralisias ou polineuropatias?', "document_label": 'Paralisias ou polineuropatias?'},
            {"key": 'is_parkinson', "label": 'Parkinson?', "document_label": 'Parkinson?'},
            {"key": 'is_ame', "label": 'Atrofia Muscular Espinhal (AME)?', "document_label": 'Possui Atrofia Muscular Espinhal (AME): doença neurológica progressiva que leva a perda de força, movimentos, capacidade de engolir e respirar'},
        ],
    },
    {
        "number": 8,
        "title": 'Sofre ou sofreu de doenças dos olhos e anexos?',
        "document_title": 'Sofre ou sofreu de doenças dos olhos e anexos?',
        "items": [
            {"key": 'is_alteracao_retina', "label": 'Alterações na retina?', "document_label": 'Alterações na retina?'},
            {"key": 'is_astigmatismo', "label": 'Astigmatismo?', "document_label": 'Astigmatismo?'},
            {"key": 'is_catarata', "label": 'Catarata?', "document_label": 'Catarata?'},
            {"key": 'is_ceratocone', "label": 'Ceratocone?', "document_label": 'Ceratocone?'},
            {"key": 'is_estrabismo', "label": 'Estrabismo?', "document_label": 'Estrabismo?'},
            {"key": 'is_glaucoma', "label": 'Glaucoma?', "document_label": 'Glaucoma?'},
            {"key": 'is_hipermetropia', "label": 'Hipermetropia?', "document_label": 'Hipermetropia?'},
            {"key": 'is_miopia', "label": 'Miopia?', "document_label": 'Miopia?'},
            {"key": 'is_transplante_cornea', "label": 'Necessidade de transplante de córnea?', "document_label": 'Necessidade de transplante de córnea?'},
            {"key": 'is_pterigio', "label": 'Pterígio?', "document_label": 'Pterígio?'},
            {"key": 'is_retinopatia_diabetica', "label": 'Retinopatia diabética?', "document_label": 'Retinopatia diabética?'},
            {"key": 'is_presbiopia', "label": 'Presbiopia (queda da visão para perto)?', "document_label": 'Presbiopia? (Queda da visão para perto)'},
        ],
    },
    {
        "number": 9,
        "title": 'Sofre ou sofreu de doenças do ouvido, nariz ou garganta?',
        "document_title": 'Sofre ou sofreu de doenças do ouvido, nariz ou garganta?',
        "items": [
            {"key": 'is_diminuicao_audicao', "label": 'Diminuição da audição, perfuração do tímpano, infecções frequentes?', "document_label": 'Diminuição da audição, perfuração do tímpano, infecções frequentes?'},
            {"key": 'is_hipertrofia_cornetos_amigdalas', "label": 'Hipertrofia de cornetos ou amígdalas?', "document_label": 'Hipertrofia de cornetos ou amígdalas?'},
            {"key": 'is_labirintite', "label": 'Labirintite?', "document_label": 'Labirintite?'},
            {"key": 'is_rinite', "label": 'Rinite?', "document_label": 'Rinite?'},
            {"key": 'is_sinusite', "label": 'Sinusite?', "document_label": 'Sinusite?'},
            {"key": 'is_problemas_adenoide', "label": 'Problemas de adenoide, tumor, desvio de septo, pólipos?', "document_label": 'Problemas de adenóide, tumor, desvio de septo, pólipos?'},
        ],
    },
    {
        "number": 10,
        "title": 'Sofre ou sofreu de doenças do coração?',
        "document_title": 'Sofre ou sofreu de doenças do coração?',
        "items": [
            {"key": 'is_angina_pectoris', "label": 'Angina pectoris?', "document_label": 'Angina pectoris?'},
            {"key": 'is_arritmia_cardiaca', "label": 'Arritmia cardíaca?', "document_label": 'Arritmia cardíaca?'},
            {"key": 'is_disfuncao_valvulas', "label": 'Doenças com disfunção de válvulas?', "document_label": 'Doenças com disfunção de válvulas?'},
            {"key": 'is_hipertensao_arterial', "label": 'Hipertensão arterial ou doença hipertensiva da gravidez?', "document_label": 'Hipertensão arterial ou Doença hipertensiva da gravidez?'},
            {"key": 'is_infarto_miocardio', "label": 'Infarto do miocárdio?', "document_label": 'Infarto do miocárdio?'},
            {"key": 'is_insuficiencia_cardiaca', "label": 'Insuficiência cardíaca?', "document_label": 'Insuficiência cardíaca?'},
            {"key": 'is_insuficiencia_coronariana', "label": 'Insuficiência coronariana?', "document_label": 'Insuficiência coronariana?'},
            {"key": 'is_uso_marcapasso', "label": 'Uso de marca-passo?', "document_label": 'Uso de marcapasso'},
        ],
    },
    {
        "number": 11,
        "title": 'Sofre ou sofreu de doenças do sistema circulatório?',
        "document_title": 'Sofre ou sofreu de doenças do sistema circulatório?',
        "items": [
            {"key": 'is_aneurismas', "label": 'Aneurismas?', "document_label": 'Aneurismas?'},
            {"key": 'is_hemorroidas', "label": 'Hemorroidas?', "document_label": 'Hemorróidas?'},
            {"key": 'is_insuficiencia_arterial_periferica', "label": 'Insuficiência arterial periférica?', "document_label": 'Insuficiência arterial periférica?'},
            {"key": 'is_trombose_tromboflebite', "label": 'Trombose ou tromboflebite?', "document_label": 'Trombose ou Trombo flebites?'},
            {"key": 'is_ulcera_perna', "label": 'Úlcera de perna?', "document_label": 'Úlcera de perna?'},
            {"key": 'is_varizes', "label": 'Varizes de membros inferiores ou microvarizes?', "document_label": 'Varizes de membros inferiores ou Micro varizes?'},
        ],
    },
    {
        "number": 12,
        "title": 'Sofre ou sofreu de doenças do sistema respiratório?',
        "document_title": 'Sofre ou sofreu de doenças do sistema respiratório?',
        "items": [
            {"key": 'is_apneia_sono', "label": 'Apneia do sono?', "document_label": 'Apnéia do sono?'},
            {"key": 'is_asma', "label": 'Asma?', "document_label": 'Asma?'},
            {"key": 'is_bronquiectasia', "label": 'Bronquiectasia (dilatação do brônquio)?', "document_label": 'Bronquiectasia? (Dilatação do brônquio)'},
            {"key": 'is_bronquite', "label": 'Bronquite?', "document_label": 'Bronquite?'},
            {"key": 'is_enfisema_dpoc', "label": 'Enfisema (DPOC)?', "document_label": 'Enfisema?(DPOC)'},
            {"key": 'is_fibrose_pulmonar', "label": 'Fibrose pulmonar?', "document_label": 'Fibrose pulmonar?'},
            {"key": 'is_pneumonia', "label": 'Pneumonia?', "document_label": 'Pneumonia?'},
        ],
    },
    {
        "number": 13,
        "title": 'Sofre ou sofreu de doenças do sistema digestivo?',
        "document_title": 'Sofre ou sofreu de doenças do sistema digestivo?',
        "items": [
            {"key": 'is_cirrose_hepatica', "label": 'Cirrose hepática?', "document_label": 'Cirrose hepática?'},
            {"key": 'is_colelitiase', "label": 'Colelitíase (cálculo da vesícula)?', "document_label": 'Colelitíase (cálculo da vesícula)?'},
            {"key": 'is_colite', "label": 'Colite?', "document_label": 'Colite?'},
            {"key": 'is_doenca_diverticular', "label": 'Doença diverticular do intestino (diverticulite)?', "document_label": 'Doença diverticular do intestino (diverticulite)?'},
            {"key": 'is_doencas_pancreas', "label": 'Doenças do pâncreas?', "document_label": 'Doenças do pâncreas?'},
            {"key": 'is_gastrite', "label": 'Gastrite?', "document_label": 'Gastrite?'},
            {"key": 'is_ulcera_peptica', "label": 'Úlcera péptica?', "document_label": 'Úlcera péptica?'},
            {"key": 'is_hepatite_digestiva', "label": 'Hepatites (doença digestiva)?', "document_label": 'Hepatites?'},
            {"key": 'is_esteatose_hepatica', "label": 'Esteatose hepática?', "document_label": 'Esteatose Hepática'},
        ],
    },
    {
        "number": 14,
        "title": 'Sofre ou sofreu de algum tipo de hérnia?',
        "document_title": 'Sofre ou sofreu de algum tipo de Hérnia?',
        "items": [
            {"key": 'is_hernia_inguinal', "label": 'Inguinal?', "document_label": 'Inguinal?'},
            {"key": 'is_hernia_hiato', "label": 'De hiato?', "document_label": 'De Hiato?'},
            {"key": 'is_hernia_umbilical', "label": 'Umbilical?', "document_label": 'Umbilical?'},
            {"key": 'is_hernia_epigastrica', "label": 'Epigástrica?', "document_label": 'Epigástrica?'},
            {"key": 'is_hernia_incisional', "label": 'Incisional?', "document_label": 'Incisional?'},
        ],
    },
    {
        "number": 15,
        "title": 'Sofre ou sofreu de doenças da pele?',
        "document_title": 'Sofre ou sofreu de doenças da pele? (Especifique o local)',
        "items": [
            {"key": 'is_tumores_pele', "label": 'Tumores?', "document_label": 'Tumores?'},
            {"key": 'is_nodulos_cistos', "label": 'Nódulos ou cistos?', "document_label": 'Nódulos ou cistos?'},
            {"key": 'is_queloide', "label": 'Quelóide?', "document_label": 'Quelóide?'},
        ],
    },
    {
        "number": 16,
        "title": 'Sofre ou sofreu de doenças osteomusculares e/ou da coluna?',
        "document_title": 'Sofre ou sofreu de doenças osteomusculares e/ou da coluna? Especifique o local',
        "items": [
            {"key": 'is_artrite', "label": 'Artrite?', "document_label": 'Artrite?'},
            {"key": 'is_artrite_reumatoide', "label": 'Artrite reumatóide?', "document_label": 'Artrite Reumatóide?'},
            {"key": 'is_artrose', "label": 'Artrose?', "document_label": 'Artrose?'},
            {"key": 'is_desvios_coluna', "label": 'Desvios da coluna (escoliose ou lordose)?', "document_label": 'Desvios da coluna? Escoliose ou Lordose?'},
            {"key": 'is_esclerodermia', "label": 'Esclerodermia?', "document_label": 'Esclerodermia?'},
            {"key": 'is_calos_osseos', "label": 'Calos ósseos?', "document_label": 'Calos ósseos?'},
            {"key": 'is_sequelas_fraturas', "label": 'Sequelas de fraturas?', "document_label": 'Sequelas de Fraturas?'},
            {"key": 'is_hernia_disco', "label": 'Hérnia de disco?', "document_label": 'Hérnia de disco?'},
            {"key": 'is_lupus', "label": 'Lúpus eritematoso sistêmico?', "document_label": 'Lúpus eritematoso sistêmico?'},
            {"key": 'is_osteomielite', "label": 'Osteomielite?', "document_label": 'Osteomielite?'},
            {"key": 'is_osteoporose', "label": 'Osteoporose?', "document_label": 'Osteoporose?'},
            {"key": 'is_reumatismo', "label": 'Reumatismo?', "document_label": 'Reumatismo?'},
            {"key": 'is_tendinite', "label": 'Tendinite?', "document_label": 'Tendinite?'},
            {"key": 'is_dores_coluna', "label": 'Dores na coluna (lombociatalgia ou outras dores cervical/torácica)?', "document_label": 'Dores na coluna? Lombociatalgia ou outras dores de coluna cervical ou torácica?'},
        ],
    },
    {
        "number": 17,
        "title": 'Sofreu ou sofre de doenças do aparelho urinário?',
        "document_title": 'Sofreu ou sofre de doenças do aparelho urinário?',
        "items": [
            {"key": 'is_calculo_renal', "label": 'Cálculo renal, ureteral ou de bexiga?', "document_label": 'Cálculo renal, ureteral e de bexiga?'},
            {"key": 'is_incontinencia_urinaria', "label": 'Incontinência urinária?', "document_label": 'Incontinência urinária (“urina solta”)?'},
            {"key": 'is_insuficiencia_renal', "label": 'Insuficiência renal (aguda ou crônica)?', "document_label": 'Insuficiência renal? ( )Aguda ( ) Crônica'},
            {"key": 'is_transplante_renal', "label": 'Necessidade de transplante renal?', "document_label": 'Necessidade de transplante renal?'},
            {"key": 'is_nefrite_nefrose', "label": 'Nefrite ou nefrose?', "document_label": 'Nefrite ou nefrose ?'},
        ],
    },
    {
        "number": 18,
        "title": 'Sofre ou sofreu de doenças do aparelho genital feminino?',
        "document_title": 'Sofre ou sofreu de doenças do aparelho genital feminino?',
        "items": [
            {"key": 'is_cisto_ovario', "label": 'Cisto de ovário?', "document_label": 'Cisto de ovário?'},
            {"key": 'is_endometriose', "label": 'Endometriose?', "document_label": 'Endometriose?'},
            {"key": 'is_infertilidade_feminina', "label": 'Infertilidade?', "document_label": 'Infertilidade?'},
            {"key": 'is_nodulo_mamario', "label": 'Nódulo mamário?', "document_label": 'Nódulo mamário?'},
            {"key": 'is_prolapso_uterino', "label": 'Prolapso uterino?', "document_label": 'Prolapso uterino?'},
            {"key": 'is_ruptura_perineal', "label": 'Ruptura perineal ou outras?', "document_label": 'Ruptura perineal ou outras?'},
        ],
    },
    {
        "number": 19,
        "title": 'Sofre ou sofreu de doenças do aparelho genital masculino?',
        "document_title": 'Sofre ou sofreu de doenças do aparelho genital masculino?',
        "items": [
            {"key": 'is_esterilidade', "label": 'Esterilidade?', "document_label": 'Esterilidade?'},
            {"key": 'is_fimose', "label": 'Fimose?', "document_label": 'Fimose?'},
            {"key": 'is_hiperplasia_prostata', "label": 'Hiperplasia de próstata?', "document_label": 'Hiperplasia de próstata?'},
            {"key": 'is_hipospadia', "label": 'Hipospadia?', "document_label": 'Hipospadia?'},
            {"key": 'is_impotencia_sexual', "label": 'Impotência sexual?', "document_label": 'Impotência Sexual?'},
            {"key": 'is_testiculo_alto', "label": 'Testículo alto (fora da bolsa escrotal)?', "document_label": 'Testículo alto? (fora da bolsa escrotal)'},
            {"key": 'is_varicocele', "label": 'Varicocele?', "document_label": 'Varicocele?'},
        ],
    },
    {
        "number": 20,
        "title": 'Sofre ou sofreu de doença bucomaxilar?',
        "document_title": 'Sofre ou sofreu de doença bucomaxilo?',
        "items": [
            {"key": 'is_micrognatia', "label": 'Micrognatia?', "document_label": 'Micrognatia?'},
            {"key": 'is_prognatia', "label": 'Prognatia?', "document_label": 'Prognatia?'},
            {"key": 'is_alteracao_maxila', "label": 'Alteração da maxila?', "document_label": 'Alteração da maxila?'},
            {"key": 'is_alteracao_atm', "label": 'Alteração da articulação temporomandibular (ATM)?', "document_label": 'Alteração da articulação temporomandibular (ATM)?'},
            {"key": 'is_ma_formacao_arcada_dentaria', "label": 'Má formação da arcada dentária?', "document_label": 'Má formação da arcada dentária?'},
            {"key": 'is_uso_aparelho_ortodontico', "label": 'Usou ou usa aparelho ortodôntico?', "document_label": 'Usou ou usa aparelho ortodôntico?'},
        ],
    },
    {
        "number": 21,
        "title": 'Traumatismos e/ou fraturas',
        "document_title": 'Sofre ou sofreu de traumatismos e/ou fraturas?',
        "items": [
            {"key": 'is_traumatismos_fraturas', "label": 'Já sofreu traumatismos e/ou fraturas?', "document_label": ''},
        ],
    },
    {
        "number": 22,
        "title": 'Sequelas de acidentes ou doença congênita',
        "document_title": 'Sofre de sequelas de acidentes, moléstia adquirida ou congênita (doenças de nascença)?',
        "items": [
            {"key": 'is_sequelas_acidentes_congenitas', "label": 'Sofre de sequelas de acidentes, moléstia adquirida ou congênita (doença de nascença)?', "document_label": ''},
        ],
    },
    {
        "number": 23,
        "title": 'Cirurgias já realizadas',
        "document_title": 'Já foi submetido a algum tipo de cirurgia?',
        "items": [
            {"key": 'is_cirurgia_previa', "label": 'Já foi submetido a algum tipo de cirurgia?', "document_label": ''},
        ],
    },
    {
        "number": 24,
        "title": 'Internação ou tratamento não relacionado às doenças acima',
        "document_title": 'Sofre ou sofreu de alguma doença não relacionada acima, que o tenha obrigado a internar-se ou submeter-se a algum tipo de tratamento ou exame?',
        "items": [
            {"key": 'is_internacao_tratamento_outro', "label": 'Sofre ou sofreu de alguma doença não relacionada acima que o tenha obrigado a internar-se ou submeter-se a algum tipo de tratamento ou exame?', "document_label": ''},
        ],
    },
    {
        "number": 25,
        "title": 'Radioterapia, quimioterapia ou diálise',
        "document_title": 'Já foi submetido à radioterapia, quimioterapia, braquiterapia, hemodiálise ou diálise peritonial?',
        "items": [
            {"key": 'is_radioterapia_quimioterapia_dialise', "label": 'Já foi submetido à radioterapia, quimioterapia, braquiterapia, hemodiálise ou diálise peritonial?', "document_label": ''},
        ],
    },
    {
        "number": 26,
        "title": 'Cirurgia futura',
        "document_title": 'Tem indicação firmada ou em avaliação de submeter-se a algum tipo de cirurgia?',
        "items": [
            {"key": 'is_indicacao_cirurgia_futura', "label": 'Tem indicação firmada ou em avaliação de submeter-se a algum tipo de cirurgia?', "document_label": ''},
        ],
    },
    {
        "number": 27,
        "title": 'Prótese ou órtese',
        "document_title": 'Possui algum tipo de prótese ou órtese (placas, pinos, parafusos, marca-passo, outros)?',
        "items": [
            {"key": 'is_protese_ortese', "label": 'Possui algum tipo de prótese ou órtese (placas, pinos, parafusos, marca-passo, outros)?', "document_label": ''},
        ],
    },
]

# só as perguntas Sim/Não do banco: peso, altura, idade e IMC não são perguntas
QUALIFY_INTERVIEW_QUESTIONS = [
    item
    for group in QUALIFY_INTERVIEW_GROUPS
    for item in group["items"]
    if not item.get("type")
]

QUALIFY_INTERVIEW_TOTAL_QUESTIONS = len(QUALIFY_INTERVIEW_QUESTIONS)
